#! /bin/bash

OUTDIR="out"

# if command line arguments supplied -> run on given phrase
if [ $# -ge 1 ]; then
	phrase="$*"
	python lookup_word.py $phrase

# if no arguments supplied -> run on speech
else
	export OUTDIR

	if [ ! -d $OUTDIR ]; then
		mkdir $OUTDIR;
	fi

	prefix="./"
	slash="/"
	name="analysis" 
	current_time=$(date "+_%Y.%m.%d-%H.%M.%S")
	ext=.txt

	export FED_SENTIMENT_ANLYSIS_TIME=$current_time

	file_name=$prefix$OUTDIR$slash$name$current_time$ext

	python analysis.py > $file_name

	unset OUTDIR
	unset FED_SENTIMENT_ANLYSIS_TIME
fi